CREATE TABLE ADMIN_PANEL.USERS
(
  FIRST_NAME  VARCHAR2(25 BYTE)                 NOT NULL,
  LAST_NAME   VARCHAR2(25 BYTE)                 NOT NULL,
  EMAIL       VARCHAR2(45 BYTE)                 NOT NULL,
  USER_NAME   VARCHAR2(25 BYTE)                 NOT NULL,
  PASSWORD    VARCHAR2(64 BYTE)                 NOT NULL
)